
import Animals.Animal;
import com.jwetherell.algorithms.data_structures.Graph;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author Krieolin
 */
public class chatform extends javax.swing.JFrame {

    private static int chatPartnerLocation = 0;
    private static Animal chatAnimal;
    private static Animal userAnimal;
    private static int messageResponce = 0;
    private static int messageResponceFriend = 0;
    private static boolean isFriend = false;

    /**
     * Creates new form chatform
     */
    public chatform() {
        initComponents();
        setDisplay();
        CustomCusor();
    }
    
    //cusor method
    public void CustomCusor() {
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        // Image img = toolkit.getImage("src\\images\\cusor.png");
        ImageIcon icon = new ImageIcon(getClass().getResource("cusor.png"));
        Image img = icon.getImage();
        //part of curso pointer
        Point point = new Point(1, 1);
        Cursor cursor = toolkit.createCustomCursor(img, point, "Cursor");
        setCursor(cursor);
    }

    //sets up the display
    public void setDisplay() {
        getChatPartner();
        //ImageIcon icon = new ImageIcon(chatAnimal.getimagePath());
        //  ImageIcon icon = new ImageIcon(chatAnimal.getimagePath());
        ImageIcon icon = new ImageIcon(getClass().getResource(chatAnimal.getimagePath()));
        //scaling image to fit in jlael

        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(lblfriendimage.getWidth(), lblfriendimage.getHeight(), Image.SCALE_SMOOTH);
        //lblimage.setIcon(icon);
        ImageIcon scaledImage = new ImageIcon(imgScale);
        lblfriendimage.setIcon(scaledImage);

        String strFriend = "Name: " + chatAnimal.getName() + "\n";
        strFriend += "Description: " + chatAnimal.getDescription() + "\n";

        txtareafriend.setText(strFriend);

        //sets user
        // ImageIcon icon2 = new ImageIcon(userAnimal.getimagePath());
//ImageIcon icon2 = new ImageIcon(userAnimal.getimagePath());    
        ImageIcon icon2 = new ImageIcon(getClass().getResource(userAnimal.getimagePath()));
//scaling image to fit in jlael

        Image img2 = icon2.getImage();
        Image imgScale2 = img2.getScaledInstance(lbluserimage.getWidth(), lbluserimage.getHeight(), Image.SCALE_SMOOTH);
        //lblimage.setIcon(icon);
        ImageIcon scaledImage2 = new ImageIcon(imgScale2);
        lbluserimage.setIcon(scaledImage2);

        String strUser = "Name: " + userAnimal.getName() + "\n";
        strUser += "Description: " + userAnimal.getDescription() + "\n";
        txtareauser.setText(strUser);

        txtareachat.setText("This is the start of your chat history with " + chatAnimal.getName() + " why don't you start the chat by staying 'hi' \n");

    }

    //gets the chat partner
    public void getChatPartner() {
        Graph<Animal> g = Filehandlers.GetFromFile();
        int size = 0;
        chatAnimal = null;
        String str = "";
        int displaySize = 1;
        Graph.Vertex<Animal> to = null;
        Graph.Vertex<Animal> from = null;

        for (Graph.Vertex v : g.getVertices()) {
            if (size == chatPartnerLocation) {
                chatAnimal = g.getVertices().get(size).getValue();
                to = g.getVertices().get(size);
            }
            if (loggedInInfo.getUsername().equals(g.getVertices().get(size).getValue().getUsername()) && loggedInInfo.getPassword().equals(g.getVertices().get(size).getValue().getPassword())) {
                userAnimal = g.getVertices().get(size).getValue();
                from = g.getVertices().get(size);
            }
            str += displaySize + "." + g.getVertices().get(size).getValue().getName() + " friend: " + g.getVertices().get(size).getEdges() + "\n";
            displaySize += 1;
            size += 1;
        }

        if (chatAnimal == null) {
            chatAnimal = g.getVertices().get(1).getValue();
            to = g.getVertices().get(1);
        }
        if (userAnimal == null) {
            userAnimal = chatAnimal;
            from = g.getVertices().get(2);
        }

        Graph.Edge<Animal> edge = new Graph.Edge<>(10, to, from);
        g.getEdges().add(edge);
        Filehandlers.saveToFile(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelchat = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtareachat = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        txtfielduser = new javax.swing.JTextField();
        btnsend = new javax.swing.JButton();
        paneluser = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbluserimage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtareauser = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblfriendimage = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtareafriend = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuUpdate = new javax.swing.JMenu();
        menuitemupdate = new javax.swing.JMenuItem();
        menuitemdelete = new javax.swing.JMenuItem();
        menuitemUserprofile = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuitemfriend = new javax.swing.JMenuItem();
        menuAnalytics = new javax.swing.JMenu();
        menuitemgender = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        menuLogout = new javax.swing.JMenu();
        menuitem1SignOut = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chat");

        txtareachat.setEditable(false);
        txtareachat.setColumns(20);
        txtareachat.setLineWrap(true);
        txtareachat.setRows(5);
        txtareachat.setWrapStyleWord(true);
        jScrollPane3.setViewportView(txtareachat);

        jLabel3.setText("Messages");

        btnsend.setText("Send");
        btnsend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelchatLayout = new javax.swing.GroupLayout(panelchat);
        panelchat.setLayout(panelchatLayout);
        panelchatLayout.setHorizontalGroup(
            panelchatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelchatLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelchatLayout.createSequentialGroup()
                .addGroup(panelchatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                    .addGroup(panelchatLayout.createSequentialGroup()
                        .addComponent(txtfielduser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnsend)))
                .addContainerGap())
        );
        panelchatLayout.setVerticalGroup(
            panelchatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelchatLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelchatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnsend, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfielduser, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel1.setText("You");

        txtareauser.setColumns(20);
        txtareauser.setLineWrap(true);
        txtareauser.setRows(5);
        txtareauser.setWrapStyleWord(true);
        txtareauser.setAutoscrolls(false);
        jScrollPane1.setViewportView(txtareauser);

        javax.swing.GroupLayout paneluserLayout = new javax.swing.GroupLayout(paneluser);
        paneluser.setLayout(paneluserLayout);
        paneluserLayout.setHorizontalGroup(
            paneluserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneluserLayout.createSequentialGroup()
                .addGroup(paneluserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneluserLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneluserLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneluserLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lbluserimage, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        paneluserLayout.setVerticalGroup(
            paneluserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneluserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(lbluserimage, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jLabel2.setText("Friend");

        txtareafriend.setColumns(20);
        txtareafriend.setLineWrap(true);
        txtareafriend.setRows(5);
        txtareafriend.setWrapStyleWord(true);
        txtareafriend.setAutoscrolls(false);
        jScrollPane2.setViewportView(txtareafriend);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lblfriendimage, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(lblfriendimage, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jMenu1.setText("Home");

        jMenuItem1.setText("Home page");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        menuUpdate.setText("User information");
        menuUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUpdateActionPerformed(evt);
            }
        });

        menuitemupdate.setText("update profile ");
        menuitemupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemupdateActionPerformed(evt);
            }
        });
        menuUpdate.add(menuitemupdate);

        menuitemdelete.setText("delete profile");
        menuitemdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemdeleteActionPerformed(evt);
            }
        });
        menuUpdate.add(menuitemdelete);

        menuitemUserprofile.setText("user profile");
        menuitemUserprofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemUserprofileActionPerformed(evt);
            }
        });
        menuUpdate.add(menuitemUserprofile);

        jMenuBar1.add(menuUpdate);

        jMenu2.setText("Friends ");

        menuitemfriend.setText("View friend list");
        menuitemfriend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemfriendActionPerformed(evt);
            }
        });
        jMenu2.add(menuitemfriend);

        jMenuBar1.add(jMenu2);

        menuAnalytics.setText("Analytics");

        menuitemgender.setText("Gender Statistics");
        menuitemgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemgenderActionPerformed(evt);
            }
        });
        menuAnalytics.add(menuitemgender);

        jMenuItem2.setText("Age Statistics");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuAnalytics.add(jMenuItem2);

        jMenuItem3.setText("Gender statistics");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuAnalytics.add(jMenuItem3);

        jMenuItem4.setText("User Statistics");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menuAnalytics.add(jMenuItem4);

        jMenuBar1.add(menuAnalytics);

        menuLogout.setText("Log out");
        menuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogoutActionPerformed(evt);
            }
        });

        menuitem1SignOut.setText("sign out");
        menuitem1SignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitem1SignOutActionPerformed(evt);
            }
        });
        menuLogout.add(menuitem1SignOut);

        jMenuBar1.add(menuLogout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(paneluser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelchat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(panelchat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(paneluser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnsendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsendActionPerformed
        // TODO add your handling code here:
        String strTextArea = txtareachat.getText();
        strTextArea += "\n" + "You: " + txtfielduser.getText();
        String returnReply = getBestReply(txtfielduser.getText());

        strTextArea += returnReply;
        txtareachat.setText(strTextArea);
        txtfielduser.setText("");


    }//GEN-LAST:event_btnsendActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        mainDisplayForm mdf = new mainDisplayForm();
        mdf.runMain();
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuitemupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemupdateActionPerformed
        // TODO add your handling code here:
        updateForm uf = new updateForm();
        uf.runMain();
        this.setVisible(false);
    }//GEN-LAST:event_menuitemupdateActionPerformed

    private void menuitemdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemdeleteActionPerformed
        // TODO add your handling code here:
        deleteform df = new deleteform();
        df.runMain();
        this.setVisible(false);
    }//GEN-LAST:event_menuitemdeleteActionPerformed

    private void menuitemUserprofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemUserprofileActionPerformed
        // TODO add your handling code here:

        userProfileForm upf = new userProfileForm();
        upf.runMain();
        this.setVisible(false);
    }//GEN-LAST:event_menuitemUserprofileActionPerformed

    private void menuUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUpdateActionPerformed

    }//GEN-LAST:event_menuUpdateActionPerformed

    private void menuitemfriendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemfriendActionPerformed
        // TODO add your handling code here:
        friendform ff = new friendform();
        ff.runMain();
        this.setVisible(false);
    }//GEN-LAST:event_menuitemfriendActionPerformed

    private void menuitemgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemgenderActionPerformed

        PetStatisticsFriendForm psff = new PetStatisticsFriendForm();
        psff.runMain();
        this.setVisible(false);
    }//GEN-LAST:event_menuitemgenderActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        PetStaticticsAgeForm psff = new PetStaticticsAgeForm();
        psff.runMain();
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        PetStatisticsGenderForm psgf = new PetStatisticsGenderForm();
        psgf.runMain();
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        PetStatisticsUsers psu = new PetStatisticsUsers();
        psu.runMain();
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void menuitem1SignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitem1SignOutActionPerformed
        // TODO add your handling code here:
        loggedInInfo.setUsername("");
        loggedInInfo.setPassword("");
        welcomeForm wf = new welcomeForm();
        wf.runMain();
        this.setVisible(false);
    }//GEN-LAST:event_menuitem1SignOutActionPerformed

    private void menuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuLogoutActionPerformed

    
    //gets the best reply - originally it was going to return a string based on what you type but because there can be so many inputs i end up returns a fixed string
    public String getBestReply(String message) {

        /*
       List<String> greetingMessageList = new ArrayList();
       greetingMessageList.add("hello");
       greetingMessageList.add("hey");
       greetingMessageList.add("hi");
       greetingMessageList.add("morning");
       greetingMessageList.add("sup");
       greetingMessageList.add("whats up");
      
       List<String> secondMessageList = new ArrayList();
       secondMessageList.add("good");
       secondMessageList.add("fine");
       secondMessageList.add("well");
       secondMessageList.add("okay");
       secondMessageList.add("great");
       secondMessageList.add("no problem");
       
       for(int i = 0; i<6 ; i++)
       {
    if(message.toLowerCase().contains(greetingMessageList.get(i)))
    {
        return "\n"+chatAnimal.getName()+": Hello " + userAnimal.getName() + ", how are you doing? i hope you don't mind me calling you by your pets name, it feels more comfortable for me:P \n";

    }    
    if(message.toLowerCase().contains(secondMessageList.get(i)))
    {
        return "\nI'm doing good, i know what you're thinking i respond really fast to be honest i just have really quick fingers, i made it to the world championship of fast typers in 2019, your pet seems cool lets meet! \n";

    }        
       }
       
   
        
        return "\n"+chatAnimal.getName()+": I have to go but lets meet at the university of johannesburg's auckland park campus on saturday at 12:00 here's my whatsapp number 079 111 0141 contact me there\n I'll leave fast reply turned on, on my PC (its a text app i created :D)so you can still type to me and get some predefined answers to things you might want to know\n (note you can check the text file in the src folder called predifinedtext.txt for keywords you can type to get replies too)";
   
         */
        if (isFriend == true) {
            messageResponceFriend += 1;
            if (messageResponceFriend == 1) {
                return "\n" + chatAnimal.getName() + ": Hey buddy, how are you and " + userAnimal.getName() + " doing?\n";

            }
            if (messageResponceFriend == 2) {
                return "\n" + chatAnimal.getName() + ": I'm doing great, man how cool was that play date! my little " + chatAnimal.getName() + " is still warn out from all that playing!\n";

            }

            if (messageResponceFriend == 3) {
                return "\n" + chatAnimal.getName() + ": We really need to meet up again i mean who would of guessed your " + userAnimal.getBreed() + " and my " + chatAnimal.getBreed() + " would be such a great match\n";

            }

            if (messageResponceFriend == 4) {
                return "\n" + chatAnimal.getName() + ": ah damn it looks like another hour of load shedding! what an amazing unbelievable time to be alive!\n";

            }
            if (messageResponceFriend == 5) {
                return "\n" + chatAnimal.getName() + ": I have to go my laptop is about to die but you got my email send me a message and i'll respond as soon as lights get back on my side, check ya pal :D\n";
            }

            return "\nUser is currently offline\n";

        } else {
            messageResponce += 1;
            if (messageResponce == 1) {
                return "\n" + chatAnimal.getName() + ": Heyyy " + userAnimal.getName() + "!, how's it going? i hope you don't mind me calling you by your pets name, it feels more comfortable for me:P \n";

            }
            if (messageResponce == 2) {
                return "\n" + chatAnimal.getName() + ": I saw on your pets bio they like " + userAnimal.getLikes().get(0) + " my pet likes " + chatAnimal.getLikes().get(0) + " maybe it could work out between them, what do you think? \n";

            }

            if (messageResponce == 3) {
                return "\n" + chatAnimal.getName() + ": thats amazing, i know what you're thinking i respond really fast to be honest i just have really quick fingers, i made it to the world championship of fast typers in 2019, your pet seems so cool, a real swagger muffin! :D\n";

            }

            if (messageResponce == 4) {
                return "\n" + chatAnimal.getName() + ": Gosh darn my laptop is about to die! but your " + chatAnimal.getBreed() + " o m g o s h is the best thing ever! you and " + userAnimal.getName() + " are officially cool enough to be part of mine and " + chatAnimal.getName() + "'s Grand swagger masta gangsta pet club! or the GSMGP for short, we wear sun glasses and walk in slow motion its really amazing!\n";

            }
            if (messageResponce == 5) {
                return "\n" + chatAnimal.getName() + ": I have to go but lets meet at the university of johannesburg's auckland park campus on saturday at 12:00 here's my whatsapp number 079 111 0141 contact me there if you still want to chat! I have load shedding in a few minutes, but luckily whatsapp still works. Check you bud! :D\n";
            }

            return "\nUser is currently offline\n";

        }

    }

    //static runMain method 
    public static void runMain() {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new chatform().setVisible(true);
                chatPartnerLocation = 1;
            }
        });
    }

    public static void runMain(String chatType, int i) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new chatform().setVisible(true);
            }
        });

        if (chatType.equals("")) {
            isFriend = true;
        } else {
            isFriend = false;
        }
        chatPartnerLocation = i;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chatform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chatform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chatform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chatform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new chatform().setVisible(true);
                chatPartnerLocation = 1;
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblfriendimage;
    private javax.swing.JLabel lbluserimage;
    private javax.swing.JMenu menuAnalytics;
    private javax.swing.JMenu menuLogout;
    private javax.swing.JMenu menuUpdate;
    private javax.swing.JMenuItem menuitem1SignOut;
    private javax.swing.JMenuItem menuitemUserprofile;
    private javax.swing.JMenuItem menuitemdelete;
    private javax.swing.JMenuItem menuitemfriend;
    private javax.swing.JMenuItem menuitemgender;
    private javax.swing.JMenuItem menuitemupdate;
    private javax.swing.JPanel panelchat;
    private javax.swing.JPanel paneluser;
    private javax.swing.JTextArea txtareachat;
    private javax.swing.JTextArea txtareafriend;
    private javax.swing.JTextArea txtareauser;
    private javax.swing.JTextField txtfielduser;
    // End of variables declaration//GEN-END:variables
}
